# ############################################################################
# app_config.yml -- configuration for BillingGateway
# variables needed to configure gateway assumed to be in config/app_config.yml
# future gateways may need more variables (add okay); not every gateway needs
# the entire set of variables
# min required:
# gateway => gateway name selector
# gateway_url => gateway url
# gateway_seller_id=> seller_id (name, email, etc)
# gateway_site_certificate => site certificate identifier
# ############################################################################
# ############################################################################

development:
  gateway: PayPalWPS
  gateway_seller_id: seller_1229899173_biz@railscasts.com
  gateway_secret: "wild blue"
  gateway_site_certificate: WKKX2FSCFDB8C
  gateway_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  gateway: PayPalWPS
  gateway_seller_id: seller_1229899173_biz@railscasts.com
  gateway_secret: "passion pink"
  gateway_site_certificate: WKKX2FSCFDB8C
  gateway_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

production:
  gateway: PayPalWPS
  gateway_seller_id: seller_1229899173_biz@railscasts.com
  gateway_secret: "peanut clusters"
  gateway_site_certificate: WKKX2FSCFDB8C
  gateway_url: "https://www.paypal.com/cgi-bin/webscr"
